---
- name: Wait for SSH connection to host
  ansible.builtin.wait_for_connection:
    delay: "{{ one_vm_wait_delay }}"
    timeout: "{{ one_vm_wait_timeout }}"

- name: Run common provision tasks
  ansible.builtin.import_role:
    name: wandansible.provision
    tasks_from: common
